[package]
name = "git-mirror"
version = "0.8.0"
authors = ["Pascal Bach <pascal.bach@nextrem.ch>"]

[features]
native-tls = [ "hyper-native-tls" ]

[dependencies]
clap = "2.31"
chrono = "0.4"
log = "0.4"
stderrlog = "0.4.0"
slug = "0.1.3"
threadpool = "1.7.1"
hyper = "0.10.13"
hyper-native-tls = { version = "0.2.4", optional = true }
hyper-rustls = "0.6.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7.3"
fs2 = "0.4.3"
prometheus = "0.4.1"
#TODO: 1.6.0 introduced breaking changes https://github.com/stepancheg/rust-protobuf/issues/289
protobuf = "=1.5.0"
