[package]
name = "git-mirror"
version = "0.10.0"
authors = ["Pascal Bach <pascal.bach@nextrem.ch>"]

[features]

[dependencies]
clap = "2.32"
chrono = "0.4"
log = "0.4"
stderrlog = "0.4"
slug = "0.1"
rayon = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
fs2 = "0.4"
prometheus = "0.4"
reqwest = "0.9"
openssl-probe = "0.1"
junit-report = "0.1.1"

[profile.release]
lto = true
